version: '2.1'

services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./web:/web
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
      image: php:7-fpm
      volumes:
        - ./web:/web
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "trackeradmin"
      MYSQL_USER: "tuser"
      MYSQL_PASSWORD: "tpass"
      MYSQL_DATABASE: "tracker"
    volumes:
       - "./db:/var/lib/mysql"